apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template: 
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: adwera/kub-networks-users:v1
          env: 
            - name: AUTH_ADDRESS
              value: "10.106.69.107"
